// Expedition layout study. The existing expedition fixture supplies the sample data and fleet markup.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { css, SCENES, SEVEN_FLEET_HTML } from './panel-exped';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const scenes = JSON.stringify(SCENES.map(scene => ({
    ...scene,
    proposed: scene.proposed.replaceAll('src="/icons/', 'src="../public/icons/'),
})));
const fleet = JSON.stringify(SEVEN_FLEET_HTML.replaceAll('src="/icons/', 'src="../public/icons/'));
const enScenes = readFileSync(resolve(root, 'tools/preview/panel-exped-editorial-en.json'), 'utf8');

const studyCss = `
html,body{height:auto;overflow:auto}body{display:block;background:var(--bg);color:var(--text);padding:22px;font-family:system-ui,-apple-system,"Hiragino Sans",sans-serif}
.study-heading{max-width:1040px;margin:0 auto 16px}.study-heading h1{font-size:22px;line-height:1.2;margin:0 0 6px}.study-heading p{margin:0;color:var(--dim);font-size:13px;line-height:1.5}
.study-toolbar{max-width:1040px;margin:0 auto 16px;display:flex;gap:6px;flex-wrap:wrap}.study-toolbar button{border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:5px;padding:7px 10px;font-size:12px;cursor:pointer}.study-toolbar button[aria-pressed=true]{border-color:var(--brass);color:var(--text);background:color-mix(in srgb,var(--brass) 18%,var(--panel))}.study-toolbar button:focus-visible{outline:2px solid var(--sparkle);outline-offset:2px}
.study-stage{max-width:1040px;margin:auto;display:flex;align-items:flex-start;gap:24px;flex-wrap:wrap}.study-aside{max-width:330px;font-size:13px;line-height:1.55;color:var(--dim)}.study-aside h2{font-size:14px;color:var(--text);margin:0 0 6px}.study-aside p{margin:0 0 12px}.study-aside a{color:var(--sparkle)}.study-metric{font-variant-numeric:tabular-nums;margin:8px 0;color:var(--text)}
.study-app{width:370px;height:850px;overflow:hidden;display:flex;flex-direction:column;flex:none;background:var(--bg);box-shadow:0 12px 38px #0006;border:1px solid var(--line);box-sizing:border-box}.study-app #tabpanel{height:270px;flex:none;min-height:270px;overflow:hidden;padding:6px 8px;box-sizing:border-box}.study-app #tab-exped{display:flex;flex-direction:column;height:100%;min-height:0;padding:0;box-sizing:border-box;gap:0}.study-app #fleets{min-height:0;flex:1;overflow:hidden}.study-app #tabs button,.study-app #fleetnav button{pointer-events:none}
@media(max-width:600px){body{padding:12px}.study-stage{gap:16px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}@media(prefers-contrast:more){.ed-row .mark,.ed-row-value,.ed-yield-label{color:var(--text)}}
`;

const page = `<!doctype html><html lang="zh-TW"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>遠征分頁｜新排版預覽</title><style>${css}${studyCss}</style></head><body>
<div class="study-heading"><h1 id="study-title">遠征分頁｜新排版預覽</h1><p id="study-description">條件沿用專案遠征測試場景；高密度場景同時使用12項條件與四位數收益示意值。面板維持 370 × 850px、遠征資訊區維持 270px，可切換場景、語言與主題。</p></div>
<div class="study-toolbar"><button data-scene="bonus-met" data-label-zh="雙門檻 · 9 項" data-label-en="Both thresholds · 9" aria-pressed="false">雙門檻 · 9 項</button><button data-scene="unmet" data-label-zh="條件未達 · 8 項" data-label-en="Conditions unmet · 8" aria-pressed="false">條件未達 · 8 項</button><button data-scene="max-12" data-label-zh="高密度＋長華語 · 四位數" data-label-en="12 + 4-digit" aria-pressed="false">高密度＋長華語 · 四位數</button><button data-scene="four-resources" data-label-zh="四項資源壓測" data-label-en="4-resource test" aria-pressed="true">四項資源壓測</button><button data-lang="zh-TW" aria-pressed="true">繁體中文</button><button data-lang="en" aria-pressed="false">English</button><button data-theme="dark" aria-pressed="true">深色</button><button data-theme="light" aria-pressed="false">淺色</button></div>
<div class="study-stage"><div class="study-app" id="app"></div><aside class="study-aside"><h2 id="reading-title">閱讀順序</h2><p id="reading-copy">資源圖示作欄頭，成功與大成功數值沿欄對齊，方便直接比較；道具維持獨立一列，條件排在收益之後。</p><h2 id="height-title">高度安排</h2><p id="height-copy">成功門檻與大成功追加門檻分開呈現；未達項目在各組內優先列出，狀態與目前數值同列。</p><h2 id="test-values-title">壓測資料</h2><p id="test-values-note">四項資源場景以四位數示意量檢查版面，不代表遊戲收益。</p><div class="study-metric" id="measure"></div><p id="preview-note">此頁是版面預覽，數字不是目前帳號資料。</p></aside></div>
<script>
const SOURCE=${scenes};const EN_SOURCE=${enScenes};const FLEET=${fleet};
const STR={"zh-TW":{general:'一般',sortie:'出擊',exped:'遠征',factory:'工廠',logistics:'調度',fleet:'第 2 艦隊',combined:'連合',base:'基地',checks:'條件',rewards:'收益',unmet:' 項未達',met:'條件達成',count:'已符合',great:'大成功',excluded:'未列入計算',passed:'已符合',missing:'尚未符合',success:'成功',successThreshold:'成功門檻',greatThreshold:'大成功門檻',unmetCount:'項未達',metCount:'項符合',items:'道具',potential:'以下為條件達成時的收益',bonus:'含裝備加成',none:'無資料'},en:{general:'General',sortie:'Sortie',exped:'Exped.',factory:'Factory',logistics:'Logistics',fleet:'Fleet 2',combined:'Combined',base:'Base',checks:'Checks',rewards:'Rewards',unmet:' unmet',met:'Conditions met',count:'met',great:'Great success',excluded:'Excluded',passed:'Met',missing:'Unmet',success:'Success',successThreshold:'Success threshold',greatThreshold:'Great Success threshold',unmetCount:'unmet',metCount:'met',items:'Items',potential:'Rewards if conditions are met',bonus:'Equipment bonus included',none:'No data'}};
let scene='four-resources',lang='zh-TW',view='checks';
function source(){if(lang==='en'&&scene!=='unmet')return EN_SOURCE.find(x=>x.id===(scene==='four-resources'?'bonus-met':scene==='max-12'?'conditions-12':scene));return SOURCE.find(x=>x.id===(scene==='four-resources'?'bonus-met':scene))}
function data(){const p=new DOMParser().parseFromString(source().proposed,'text/html');const fleetNo=p.querySelector('.exped-fleet-lbl')?.textContent?.match(/[0-9]+/)?.[0]||'2';const option=p.querySelector('option[selected]')||p.querySelector('option');const text=option?.textContent?.trim()||'';const code=text.match(/^\\[([^\\]]+)\\]/)?.[1]||'';const time=text.match(/\\((\\d+:\\d+)\\)\\s*$/)?.[1]||'';const name=text.replace(/^\\[[^\\]]+\\]\\s*/,'').replace(/\\s*\\(\\d+:\\d+\\)\\s*$/,'');const rows=[...p.querySelectorAll('.exped-check-list .check-row')].map(n=>({ok:n.classList.contains('ok'),tier:n.dataset.tier==='great'?'great':'success',name:n.querySelector('.grow')?.textContent?.trim()||'',value:n.querySelector('.num')?.textContent?.trim()||''}));if(scene==='max-12'&&lang==='zh-TW'&&rows.length)rows[0].name='輕空母/空母/水母/裝甲空母 2艘以上';const grid=p.querySelector('.exped-yield-grid');const marks=[...grid?.querySelectorAll('.exped-status')||[]].map(n=>n.textContent?.trim()||'');const mats=[...grid?.querySelectorAll('.exped-res-line')||[]].map(n=>n.innerHTML);const items=grid?.querySelector('.exped-items-line')?.textContent?.trim()||'';if(lang==='en'&&scene==='unmet'){return{fleetNo,code,time,name:'Northern Route Maritime Escort',rows:rows.map(r=>({ok:r.ok,tier:r.tier,name:({'艦數 6 艘以上':'Fleet size: 6+ ships','旗艦 Lv50 以上':'Flagship Lv 50+','艦隊 Lv 合計 200 以上':'Total fleet Lv 200+','軽空母 1 艘以上':'Light carrier: 1+','軽巡 1 艘以上':'Light cruiser: 1+','駆逐 4 艘以上':'Destroyers: 4+','対空値合計 200 以上':'Total anti-air: 200+','対潜値合計 200 以上':'Total anti-sub: 200+'})[r.name]||r.name,value:r.value.replace('目前 ','')})),marks:['✕ Requirements not met','Not eligible'],mats,items:'Improvement Material ×1 (great success only)'}}if(lang==='zh-TW'){return{fleetNo,code,time,name:name.replaceAll('戦闘','戰鬥'),rows:rows.map(r=>({...r,name:r.name.replaceAll('軽空母','輕空母').replaceAll('軽巡','輕巡').replaceAll('駆逐','驅逐').replaceAll('対空','對空').replaceAll('対潜','對潛').replaceAll('値','值')})),marks,mats,items}}return{fleetNo,code,time,name,rows,marks,mats,items}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function chrome(){const s=STR[lang];return '<div id="header"><span class="idbox"><span class="nick">'+(lang==='en'?'Admiral':'提督')+'</span><span class="num">Lv120</span></span><span class="grow"></span><span class="stat"><img class="h-icon" src="../public/icons/ui/ship.svg" alt=""><b>198/250</b></span><span class="stat"><img class="h-icon" src="../public/icons/ui/equip.svg" alt=""><b>812/900</b></span></div><div id="tabs"><button>'+s.general+'</button><button>'+s.sortie+'</button><button class="on">'+s.exped+'</button><button>'+s.factory+'</button><button>'+s.logistics+'</button></div>'}
function fleetChrome(fleetNo){const s=STR[lang];return '<div id="fleetnav"><button'+(fleetNo==='1'?' class="on"':'')+'>1</button><button'+(fleetNo==='2'?' class="on"':'')+'>2</button><button'+(fleetNo==='3'?' class="on"':'')+'>3</button><button'+(fleetNo==='4'?' class="on"':'')+'>4</button><button>'+s.combined+'</button><span class="grow"></span><button>'+s.base+'</button></div><div id="fleets">'+(lang==='en'?FLEET.replaceAll('制空','Air').replaceAll('索敵倍率','LoS factor').replaceAll('索敵','LoS').replaceAll('航速','Speed').replaceAll('低速','Slow').replaceAll('燃料','Fuel').replaceAll('彈藥','Ammo'):FLEET)+'</div>'}
function render(){
 const s=STR[lang],d=data();
 document.documentElement.lang=lang;
 document.querySelectorAll('[data-scene]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.scene===scene));b.textContent=b.dataset[lang==='en'?'labelEn':'labelZh']});
 document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));
 const studyCopy=lang==='en'?{studyTitle:'Expedition tab | Layout preview',description:'Project expedition cases; the dense stress case combines 12 conditions with illustrative four-digit rewards. The panel is 370 × 850px, with a 270px information area. Switch scenarios, language, and theme.',readingTitle:'Reading order',reading:'Success and Great Success each take one row. Their status marker stays beside the outcome name; resource amounts align beneath the larger icon headers.',heightTitle:'Condition layout',height:'Unmet conditions appear first. Symbols and semantic colors show status, while current values stay on the same row. The 270px area has no internal scrolling.',previewNote:'This is a layout preview; amounts are not account data.'}:{studyTitle:'遠征分頁｜新排版預覽',description:'條件沿用專案遠征測試場景；高密度場景同時使用12項條件與四位數收益示意值。面板維持 370 × 850px、遠征資訊區維持 270px，可切換場景、語言與主題。',readingTitle:'閱讀順序',reading:'成功與大成功各佔一列，狀態符號緊鄰結果名稱；放大的資源圖示置於欄頭，數字仍沿欄對齊。',heightTitle:'門檻分組',height:'未達條件優先排列；符號和語意色標示狀態，目前值留在條件同列。270px 資訊區不需內部捲動。',previewNote:'此頁是版面預覽，數字不是目前帳號資料。'};
 document.title=studyCopy.studyTitle;document.getElementById('study-title').textContent=studyCopy.studyTitle;document.getElementById('study-description').textContent=studyCopy.description;
 document.getElementById('reading-title').textContent=studyCopy.readingTitle;document.getElementById('reading-copy').textContent=studyCopy.reading;document.getElementById('height-title').textContent=studyCopy.heightTitle;document.getElementById('height-copy').textContent=studyCopy.height;document.getElementById('preview-note').textContent=studyCopy.previewNote;
 document.getElementById('test-values-title').textContent=lang==='en'?'Test values':'壓測資料';
 document.getElementById('test-values-note').textContent=lang==='en'?(scene==='max-12'?'The dense scene combines 12 conditions with illustrative four-digit rewards.':'The 4-resource scene uses illustrative four-digit amounts for layout testing; they are not game rewards.'):(scene==='max-12'?'12 項場景含遠征主檔最長的華語艦種條件與四位數收益示意值，檢查雙欄換行完整；其他條件為版面壓測資料。':'四項資源場景以四位數示意量檢查版面，不代表遊戲收益。');
 const localizeMats=html=>['fuel','ammo','steel','bauxite'].reduce((out,k)=>out.replaceAll('src="../public/icons/resource/'+k+'.svg" alt=""','src="../public/icons/resource/'+k+'.svg" alt="'+(lang==='en'?{fuel:'Fuel',ammo:'Ammo',steel:'Steel',bauxite:'Bauxite'}:{fuel:'燃料',ammo:'彈藥',steel:'鋼材',bauxite:'鋁土'})[k]+'"'),html||'');
 const statusClass=(text,kind)=>/✕|×|not eligible|not met|排除|未達|不列入計算/i.test(text)?kind==='great'?'dim':'ng':kind==='great'?'gs':'ok';
 const fourResourceRows={success:'<span class="res-item"><img class="m-icon" src="../public/icons/resource/fuel.svg" alt=""> 9876</span><span class="res-item"><img class="m-icon" src="../public/icons/resource/ammo.svg" alt=""> 8765</span><span class="res-item"><img class="m-icon" src="../public/icons/resource/steel.svg" alt=""> 7654</span><span class="res-item"><img class="m-icon" src="../public/icons/resource/bauxite.svg" alt=""> 6543</span>',great:'<span class="res-item"><img class="m-icon" src="../public/icons/resource/fuel.svg" alt=""> 9999</span><span class="res-item"><img class="m-icon" src="../public/icons/resource/ammo.svg" alt=""> 9876</span><span class="res-item"><img class="m-icon" src="../public/icons/resource/steel.svg" alt=""> 8765</span><span class="res-item"><img class="m-icon" src="../public/icons/resource/bauxite.svg" alt=""> 7654</span>'};
 const parseResources=html=>{const doc=new DOMParser().parseFromString('<div>'+localizeMats(html)+'</div>','text/html');return [...doc.querySelectorAll('.res-item')].map((node,index)=>{const image=node.querySelector('.m-icon');const source=image?.getAttribute('src')||'';const key=source.split('/').pop()?.replace('.svg','')||'other-'+index;const text=node.textContent?.trim()||'';const parts=text.split(' ');return{key,label:image?.getAttribute('alt')||parts[0]||'Resource',icon:image?.outerHTML||'',amount:image?text:parts.slice(1).join(' ')}})};
 const successResources=parseResources(scene==='four-resources'||scene==='max-12'?fourResourceRows.success:d.mats[0]||'');
 const greatResources=parseResources(scene==='four-resources'||scene==='max-12'?fourResourceRows.great:d.mats[1]||'');
 const resourceKeys=['fuel','ammo','steel','bauxite'];
 const resourceNames=lang==='en'?{fuel:'Fuel',ammo:'Ammo',steel:'Steel',bauxite:'Bauxite'}:{fuel:'燃料',ammo:'彈藥',steel:'鋼材',bauxite:'鋁土'};
 const resourceHeaders=resourceKeys.map(key=>'<th class="exped-resource-head" scope="col" aria-label="'+resourceNames[key]+'" title="'+resourceNames[key]+'"><img class="m-icon" src="../public/icons/resource/'+key+'.svg" alt=""></th>').join('');
 const statusSummary=(status,kind)=>{const cls=statusClass(status,kind),excluded=/not eligible|excluded|排除|未達|不列入計算/i.test(status);if(kind==='success')return cls==='ng'?'✕':'✓';if(excluded)return'—';return status||'—'};
 const outcomeRow=(label,status,kind,resources)=>'<tr><th scope="row" class="exped-outcome-label"><span class="exped-outcome-name">'+label+'</span><span class="exped-outcome-status '+statusClass(status,kind)+'" aria-label="'+esc(status||label)+'" title="'+esc(status||'')+'">'+esc(statusSummary(status,kind))+'</span></th>'+resourceKeys.map(key=>{const item=resources.find(resource=>resource.key===key);return'<td class="exped-resource-value">'+(item?esc(item.amount):'0')+'</td>'}).join('')+'</tr>';
 const resourceTable='<table class="exped-resource-matrix" aria-label="'+(lang==='en'?'Expedition resource rewards':'遠征資源收益')+'"><colgroup><col class="exped-resource-stub"><col><col><col><col></colgroup><thead><tr><th class="exped-resource-stub" scope="col"><span class="sr-only">'+(lang==='en'?'Outcome':'結果')+'</span></th>'+resourceHeaders+'</tr></thead><tbody>'+outcomeRow(s.success,d.marks[0]||'','success',successResources)+outcomeRow(s.great,d.marks[1]||'','great',greatResources)+'</tbody></table>';
 const itemsRow=d.items?'<div class="exped-items-row"><span class="exped-items-label">'+s.items+'</span><div class="exped-items-line">'+esc(d.items)+'</div></div>':'';
 const rewards='<div class="exped-yields">'+resourceTable+itemsRow+'</div>';
 const renderRows=rows=>rows.map(r=>'<div class="check-row '+(r.ok?'ok':'ng')+'" role="listitem"><span class="mark" aria-hidden="true">'+(r.ok?'✓':'✕')+'</span><span class="sr-only">'+(lang==='en'?(r.ok?'Condition met':'Condition not met'):(r.ok?'條件達成':'條件未達'))+'</span><span class="grow" title="'+esc(r.name)+'">'+esc(r.name)+'</span>'+(r.value?'<span class="num'+(r.ok?'':' ng')+'">'+esc(r.value)+'</span>':'')+'</div>').join('');
 const ordered=[{key:'success',label:s.successThreshold},{key:'great',label:s.greatThreshold}].map(tier=>{const rows=d.rows.filter(row=>(row.tier||'success')===tier.key);if(!rows.length)return'';const failed=rows.filter(row=>!row.ok),passed=rows.filter(row=>row.ok),count=lang==='en'?(failed.length?failed.length+' unmet':passed.length+' met'):(failed.length?failed.length+' 項未達':passed.length+' 項符合');return'<section class="exped-check-tier" aria-label="'+esc(tier.label)+'"><h3 class="exped-tier-heading"><span>'+tier.label+'</span><span class="exped-tier-count'+(failed.length?' has-unmet':'')+'">'+count+'</span></h3><div class="exped-check-group" role="list">'+renderRows([...failed,...passed])+'</div></section>'}).join('');
 const fleetName=s.fleet.replace(/[0-9]+/,d.fleetNo);
 const missionOption='['+d.code+'] '+d.name+(d.time?' ('+d.time+')':'');
 document.getElementById('app').innerHTML=chrome()+'<div id="tabpanel" class="has-exped"><div id="tab-exped"><div class="exped-header"><span class="exped-fleet-lbl">'+fleetName+'</span><select id="exped-select" class="exped-select" aria-label="'+(lang==='en'?'Expedition':'遠征')+'"><option selected>'+esc(missionOption)+'</option></select></div><div id="exped-check">'+rewards+'<div class="exped-conditions">'+ordered+'</div></div></div></div>'+fleetChrome(d.fleetNo);
 measure();
}
function measure(){
 const app=document.getElementById('app'),panel=app.querySelector('#tabpanel'),fleet=app.querySelector('#fleets'),conditions=app.querySelector('.exped-conditions'),yields=app.querySelector('.exped-yields');
 const lastShip=fleet.querySelector('.ship:last-of-type'),bottom=Math.round((lastShip||fleet).getBoundingClientRect().bottom-app.getBoundingClientRect().top);
 const conditionRect=conditions.getBoundingClientRect(),panelRect=panel.getBoundingClientRect(),conditionRows=[...conditions.querySelectorAll('.check-row')],headings=[...conditions.querySelectorAll('.exped-tier-heading')];
 const headingOverflow=headings.some(heading=>{const headingRect=heading.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(heading);const textRect=range.getBoundingClientRect();return textRect.top<headingRect.top-1||textRect.bottom>headingRect.bottom+1;});
 const conditionOverflow=headingOverflow||conditions.scrollHeight>conditions.clientHeight||conditions.scrollWidth>conditions.clientWidth||conditionRows.some(row=>{const rect=row.getBoundingClientRect();return rect.bottom>conditionRect.bottom+1||rect.right>conditionRect.right+1;});
 const yieldOverflow=yields.scrollHeight>yields.clientHeight||yields.getBoundingClientRect().bottom>panelRect.bottom+1;
 document.getElementById('measure').textContent=lang==='en'?'Expedition area '+Math.round(panel.getBoundingClientRect().height)+'px · 7 ships end at '+bottom+'px · '+conditions.querySelectorAll('.check-row').length+' conditions · '+(conditionOverflow||yieldOverflow?'overflows':'all visible, no scrolling'):'遠征區 '+Math.round(panel.getBoundingClientRect().height)+'px；七船底緣 '+bottom+'px；條件 '+conditions.querySelectorAll('.check-row').length+' 項 · '+(conditionOverflow||yieldOverflow?'超出可用高度':'完整顯示、無捲軸');
}
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{scene=b.dataset.scene;view='checks';render()});document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;if(lang==='zh-TW'&&scene==='english-long-name')scene='unmet';view='checks';render()});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{document.documentElement.dataset.theme=b.dataset.theme;document.querySelectorAll('[data-theme]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});render();
</script></body></html>`;
mkdirSync(resolve(root, '.preview'), { recursive: true });
const output = resolve(root, '.preview/panel-exped-editorial.html');
writeFileSync(output, page);
console.log(output);
